reporting:
  enabled: true
  channel: '1161675989961670746'
profanity:
  enabled: true
  words: []
  delete: false
  exclude-nsfw: true
  warn:
    enabled: true
    message: 'Please refrain from using profanity.'
spam:
  enabled: true
  words: []
  threshold: 3
  time: 10
  ban: false
ignore-bots: true
